version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: hourly
    open-pull-requests-limit: 10 
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "12:25"
  open-pull-requests-limit: 10
